import { getRegisteredDisplayName } from './paymentMethodRegistry';

/**
 * Payment method display names.
 */
const PAYMENT_METHOD_NAMES: Record<string, string> = {
  card: 'Card',
  visa: 'VISA',
  mastercard: 'Mastercard',
  amex: 'American Express',
  discover: 'Discover',
  jcb: 'JCB',
  unionpay: 'UnionPay',
  diners: 'Diners',
  applepay: 'Apple Pay',
  googlepay: 'Google Pay',
  wechatpay: 'WeChat Pay',
  alipaycn: 'Alipay',
  alipayhk: 'AlipayHK',
  gcash: 'GCash',
  dana: 'DANA',
  kakaopay: 'Kakao Pay',
  tng: "Touch 'n Go",
  rabbit_line_pay: 'Rabbit LINE Pay',
  truemoney: 'TrueMoney',
  online_banking: 'Online banking',
  bank_transfer: 'Bank transfer',
  fpx: 'FPX',
  poli: 'POLI',
  permatanet: 'Permatanet',
  alfamart: 'Alfamart',
  indomaret: 'Indomaret',
  doku_ewallet: 'DOKU Wallet',
  enets: 'eNETS',
  payeasy: 'Pay-easy',
  seven_eleven: '7-Eleven',
  konbini: 'Konbini',
  spei: 'SPEI',
  tesco_lotus: 'Tesco Lotus',
  grabpay: 'GrabPay',
  skrill: 'Skrill',
  eps: 'EPS',
  giropay: 'Giropay',
  ideal: 'iDEAL',
  multibanco: 'Multibanco',
  p24: 'Przelewy24',
  sofort: 'Sofort',
  trustly: 'Trustly',
  bancontact: 'Bancontact',
  dragonpay: 'DragonPay',
  blik: 'BLIK',
  mybank: 'MyBank',
  paybybankapp: 'PayByBankApp',
  verkkopankki: 'Verkkopankki',
  maxima: 'Maxima',
  narvesen: 'Narvesen',
  paypost: 'PayPost',
  perlas_terminals: 'Perlas Terminals',
  paysafecash: 'Paysafe cash',
  paysafecard: 'Paysafe card',
  paysera: 'Paysera',
  satispay: 'Satispay',
  family_mart: 'Family Mart',
  hi_life: 'Hi-Life',
  sam_kiosk: 'SAM Kiosk',
  axs_kiosk: 'AXS Kiosk',
  bigc: 'Bigc',
  esun: 'E.Sun Bank',
  permata_atm: 'Permata ATM',
  boost: 'Boost',
  shopee_pay: 'ShopeePay',
  paypal: 'PayPal',
  payu: 'PayU',
  ovo: 'OVO',
  bitpay: 'BitPay',
  ach_direct_debit: 'ACH Direct Debit',
  bacs_direct_debit: 'BACS Direct Debit',
  sepa_direct_debit: 'SEPA Direct Debit',
  becs_direct_debit: 'BECS Direct Debit',
  eft_direct_debit: 'Pre-Authorized Debit',
  duit_now: 'DuitNow',
  pay_now: 'PayNow',
  prompt_pay: 'PromptPay',
  go_pay: 'GoPay',
  linkaja: 'LinkAja',
  jenius_pay: 'Jenius Pay',
  atome: 'Atome',
  airwallex_pay: 'Airwallex Pay',
  fps: 'FPS',
  klarna: 'Klarna',
  wero: 'Wero',
  korean_local_card: 'Korean local card',
  naver_pay: 'Naver Pay',
  payco: 'Payco',
  samsung_pay: 'SamsungPay',
  lawson: 'Lawson',
  ministop: 'Ministop',
  seicomart: 'Seicomart',
  bkash: 'bKash',
  safetypay: 'safety pay',
  upi: 'UPI',
  line_pay: 'LINE Pay',
  merpay: 'MerPay',
  d_barai: 'Dbarai',
  au_pay: 'au Pay',
  rakuten_pay: 'Rakuten',
  zip: 'Zip',
  toss_pay: 'Toss',
  payeasy_atm: 'Pay-easy ATM',
  paypay: 'PayPay',
  afterpay: 'Afterpay / Clearpay',
  payto: 'PayTo',
  laybuy: 'Laybuy',
  birdpay: 'BirdPay',
  venmo: 'Venmo',
  twint: 'Twint',
  lumi: 'Lumi',
  cash_app_pay: 'Cash App Pay',
  pix: 'PIX',
  payme: 'Payme',
  grabpay_my: 'GrabPay MY',
  grabpay_sg: 'GrabPay SG',
  lithuanian_banks: 'Lithuanian Banks',
  latvian_banks: 'Latvian Banks',
  estonian_banks: 'Estonian Banks',
  indonesian_banks: 'Indonesian Banks',
  thailand_online_banking: 'Thailand Online Banking',
  philippines_online_banking: 'Philippines Online Banking',
  tabby: 'Tabby',
  octopus: 'Octopus',
};

/**
 * Gets the display name for a payment method.
 * First checks PAYMENT_METHOD_NAMES, then registered resources, otherwise returns the value.
 *
 * @param value - Payment method id (e.g. "visa", "applepay")
 * @returns Display name for the payment method
 */
export const getPaymentMethodName = (value: string): string => {
  const key = value.toLowerCase().trim();
  const mapped = PAYMENT_METHOD_NAMES[key];
  if (mapped) {
    return mapped;
  }
  const registered = getRegisteredDisplayName(value);
  if (registered) {
    return registered;
  }
  return key;
};
